using System.Collections.Generic;
using DracoRuan.PrebuildServices.AudioSystem.Editor;
using NUnit.Framework;

namespace DracoRuan.PrebuildServices.AudioSystem.Editor.Tests
{
    /// <summary>
    /// Protects the text of the generated identifier file.
    /// </summary>
    /// <remarks>
    /// This is the risky half of the code generator, kept pure and split out of the window exactly
    /// as <c>StaticDataChainSource</c> is. Every test here works on string constants and never
    /// touches a file or the AssetDatabase, which is why they can be run without a project in a
    /// particular state.
    /// </remarks>
    [TestFixture]
    public sealed class AudioIdSourceTests
    {
        private const string Namespace = "DracoRuan.PrebuildServices.AudioSystem";

        private static AudioIdGroup Group(string className, params (string member, string value, string owner)[] members)
        {
            List<AudioIdMember> list = new List<AudioIdMember>();
            foreach ((string member, string value, string owner) in members)
                list.Add(new AudioIdMember(member, value, owner));

            return new AudioIdGroup(className, $"Ids for {className}.", list);
        }

        private static string Render(params AudioIdGroup[] groups) =>
            AudioIdSource.ForGroups(Namespace, groups, "\n").Render();

        // ---- Header ----

        [Test]
        public void Render_PutsTheAutoGeneratedMarkerNearTheTop()
        {
            string source = Render(Group("AudioId", ("Click", "Click", "Assets/A.asset")));

            Assert.That(source, Does.Contain(AudioIdSource.GeneratedMarker));
            Assert.That(source.IndexOf(AudioIdSource.GeneratedMarker, System.StringComparison.Ordinal),
                Is.LessThan(200), "Analyzers only look at the first few lines.");
        }

        [Test]
        public void Render_StatesHowManyMembersEachClassHas_SoAStaleFileShowsInADiff()
        {
            string source = Render(
                Group("AudioId", ("A", "A", "Assets/A.asset"), ("B", "B", "Assets/B.asset")),
                Group("AudioChannelId", ("Music", "Music", "Assets/Config.asset")));

            Assert.That(source, Does.Contain("AudioId: 2"));
            Assert.That(source, Does.Contain("AudioChannelId: 1"));
        }

        // ---- Members ----

        [Test]
        public void Render_EmitsOneConstPerMember()
        {
            string source = Render(Group("AudioId",
                ("Click", "Click", "Assets/A.asset"),
                ("Boom", "Boom", "Assets/B.asset")));

            Assert.That(source, Does.Contain("public const string Click = \"Click\";"));
            Assert.That(source, Does.Contain("public const string Boom = \"Boom\";"));
        }

        [Test]
        public void Render_SortsMembersOrdinally()
        {
            string source = Render(Group("AudioId",
                ("Zulu", "Zulu", "Assets/Z.asset"),
                ("Alpha", "Alpha", "Assets/A.asset")));

            Assert.That(source.IndexOf("Alpha", System.StringComparison.Ordinal),
                Is.LessThan(source.IndexOf("Zulu", System.StringComparison.Ordinal)));
        }

        [Test]
        public void Render_IsUnchangedWhenTheInputIsReordered()
        {
            string forwards = Render(Group("AudioId",
                ("Zulu", "Zulu", "Assets/Z.asset"),
                ("Alpha", "Alpha", "Assets/A.asset")));

            string backwards = Render(Group("AudioId",
                ("Alpha", "Alpha", "Assets/A.asset"),
                ("Zulu", "Zulu", "Assets/Z.asset")));

            Assert.That(forwards, Is.EqualTo(backwards),
                "Scan order must not show up as a diff in version control.");
        }

        [Test]
        public void Render_DocumentsEachMemberWithItsOwningAsset()
        {
            string source = Render(Group("AudioId", ("Click", "Click", "Assets/Game/Audio/Click.asset")));

            Assert.That(source, Does.Contain("Assets/Game/Audio/Click.asset"));
        }

        [Test]
        public void Render_EmitsAnAllListMatchingTheConstants()
        {
            string source = Render(Group("AudioId",
                ("Click", "Click", "Assets/A.asset"),
                ("Boom", "Boom", "Assets/B.asset")));

            Assert.That(source, Does.Contain("IReadOnlyList<string> All"));
            Assert.That(source, Does.Contain("Boom,"));
            Assert.That(source, Does.Contain("Click,"));
        }

        [Test]
        public void Render_EscapesAQuoteInAValue()
        {
            string source = Render(Group("AudioId", ("Odd", "we\"ird", "Assets/A.asset")));

            Assert.That(source, Does.Contain("\"we\\\"ird\""));
        }

        [Test]
        public void Render_EscapesABackslashInAValue()
        {
            string source = Render(Group("AudioId", ("Odd", "a\\b", "Assets/A.asset")));

            Assert.That(source, Does.Contain("\"a\\\\b\""));
        }

        // ---- Shape ----

        [Test]
        public void Render_PutsEveryClassInOneFile()
        {
            string source = Render(
                Group("AudioId", ("Click", "Click", "Assets/A.asset")),
                Group("AudioChannelId", ("Music", "Music", "Assets/Config.asset")));

            Assert.That(source, Does.Contain("public static class AudioId"));
            Assert.That(source, Does.Contain("public static class AudioChannelId"));
            Assert.That(source, Does.Contain($"namespace {Namespace}"));
        }

        [Test]
        public void Render_WithNoMembers_StillEmitsACompilableClass()
        {
            string source = Render(Group("AudioId"));

            Assert.That(source, Does.Contain("public static class AudioId"));
            Assert.That(source, Does.Contain("IReadOnlyList<string> All"));
            Assert.That(source, Does.Not.Contain("public const string"));
        }

        [Test]
        public void Render_UsesTheNewlineItWasGiven()
        {
            AudioIdGroup group = Group("AudioId", ("Click", "Click", "Assets/A.asset"));

            string unix = AudioIdSource.ForGroups(Namespace, new[] { group }, "\n").Render();
            string windows = AudioIdSource.ForGroups(Namespace, new[] { group }, "\r\n").Render();

            Assert.That(unix, Does.Not.Contain("\r"));
            Assert.That(windows, Does.Contain("\r\n"));
            Assert.That(windows.Replace("\r\n", "\n"), Is.EqualTo(unix),
                "Only the line endings may differ, so a rewrite never mixes them.");
        }

        // ---- Guards ----

        [Test]
        public void IsGeneratedFile_RecognisesItsOwnOutput()
        {
            string source = Render(Group("AudioId", ("Click", "Click", "Assets/A.asset")));

            Assert.That(AudioIdSource.IsGeneratedFile(source), Is.True);
        }

        [Test]
        public void IsGeneratedFile_RejectsAHandWrittenFile()
        {
            const string handWritten = "using UnityEngine;\n\npublic static class AudioId\n{\n}\n";

            Assert.That(AudioIdSource.IsGeneratedFile(handWritten), Is.False,
                "Overwriting someone's own file would be the worst thing this tool could do.");
        }

        [Test]
        public void IsGeneratedFile_RejectsEmptyOrNull()
        {
            Assert.That(AudioIdSource.IsGeneratedFile(null), Is.False);
            Assert.That(AudioIdSource.IsGeneratedFile(string.Empty), Is.False);
        }

        [Test]
        public void IsGeneratedFile_IgnoresTheMarkerFurtherDownTheFile()
        {
            string faked = new string('x', 4000) + AudioIdSource.GeneratedMarker;

            Assert.That(AudioIdSource.IsGeneratedFile(faked), Is.False);
        }

        // ---- Newline detection ----

        [Test]
        public void DetectNewLine_FindsWindowsEndings()
        {
            Assert.That(AudioIdSource.DetectNewLine("a\r\nb"), Is.EqualTo("\r\n"));
        }

        [Test]
        public void DetectNewLine_FindsUnixEndings()
        {
            Assert.That(AudioIdSource.DetectNewLine("a\nb"), Is.EqualTo("\n"));
        }

        [Test]
        public void DetectNewLine_WithNoEndings_FallsBackToUnix()
        {
            Assert.That(AudioIdSource.DetectNewLine("single line"), Is.EqualTo("\n"));
        }
    }
}
