using System.Linq;
using System.Text;
using MessagePipeSupport.Models;
using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MessagePipeSupport.Generator;

[Generator]
public class RegisterMessageFilterGenerator : IIncrementalGenerator
{
    private const string RegisterMessageFilterAttributeName = "MessageHandlerFilterAttribute";
    
    private static readonly StringBuilder RegisterMessageFilterOverallBuilder = new();
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<RegisterMessageFilterModel> classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: (syntaxContext, _) => GetRegistrationData(syntaxContext))
            .Where(registrationModel => registrationModel is not null);
        
        IncrementalValueProvider<ImmutableArray<RegisterMessageFilterModel>> registrationData = classDeclarations.Collect();
        context.RegisterSourceOutput(registrationData, Execute);
    }

    private static RegisterMessageFilterModel GetRegistrationData(GeneratorSyntaxContext context)
    {
        ClassDeclarationSyntax classDeclarationSyntax = (ClassDeclarationSyntax)context.Node;
        INamedTypeSymbol symbol = context.SemanticModel.GetDeclaredSymbol(classDeclarationSyntax) as INamedTypeSymbol;
        AttributeData attributeData = symbol?.GetAttributes().FirstOrDefault(attribute =>
            attribute.AttributeClass?.Name is RegisterMessageFilterAttributeName);

        if (attributeData == null)
            return null;
        
        string fullRequestHandlerName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        bool isAsync = false;
        
        foreach (var kvp in attributeData.NamedArguments)
        {
            switch (kvp.Key)
            {
                case "IsAsync":
                    if (kvp.Value.Value != null) 
                        isAsync = (bool)kvp.Value.Value;
                    break;
            }
        }
        
        return new RegisterMessageFilterModel(fullRequestHandlerName, isAsync);
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<RegisterMessageFilterModel> models)
    {
        if (models.IsDefaultOrEmpty)
            return;

        StringBuilder registerMessageFilterBuilder = new();
        RegisterMessageFilterOverallBuilder.Clear();
        RegisterMessageFilterOverallBuilder.AppendLine("// Authored by DracoRuan");
        RegisterMessageFilterOverallBuilder.AppendLine($"// <auto-generated Request Handlers/>");
        RegisterMessageFilterOverallBuilder.AppendLine("using VContainer;");
        RegisterMessageFilterOverallBuilder.AppendLine("using MessagePipe;");
        RegisterMessageFilterOverallBuilder.AppendLine("");
        RegisterMessageFilterOverallBuilder.AppendLine("namespace MessagePipeGeneratorSupport.RequestHandlers.Generated");
        RegisterMessageFilterOverallBuilder.AppendLine("{");
        RegisterMessageFilterOverallBuilder.AppendLine($"   public static class MessagePipeRequestHandlerExtension");
        RegisterMessageFilterOverallBuilder.AppendLine("   {");
        RegisterMessageFilterOverallBuilder.AppendLine("       public static void RegisterAllMessageFilters(this IContainerBuilder builder)");
        RegisterMessageFilterOverallBuilder.AppendLine("       {");
        
        foreach (RegisterMessageFilterModel model in models)
        {
            GetGeneratedCodeForRequestHandler(model, registerMessageFilterBuilder);
        }

        RegisterMessageFilterOverallBuilder.Append(registerMessageFilterBuilder);
        RegisterMessageFilterOverallBuilder.AppendLine("       }");
        RegisterMessageFilterOverallBuilder.AppendLine("   }");
        RegisterMessageFilterOverallBuilder.AppendLine("}");
        SourceText generatedCode = SourceText.From(RegisterMessageFilterOverallBuilder.ToString(), Encoding.UTF8);
        context.AddSource("GeneratedMessagePipeMessageFiltersRegister.g.cs", generatedCode);
    }

    private static void GetGeneratedCodeForRequestHandler(RegisterMessageFilterModel requestHandlerModel,
        StringBuilder stringBuilder)
    {
        if (!requestHandlerModel.IsAsync)
            stringBuilder.AppendLine($"            builder.RegisterMessageHandlerFilter<{requestHandlerModel.FullRequestHandlerName}>();");
        else
            stringBuilder.AppendLine($"            builder.RegisterAsyncMessageHandlerFilter<{requestHandlerModel.FullRequestHandlerName}>();");
    }
}