using System.Collections.Immutable;
using System.Linq;
using System.Text;
using MessagePipeSupport.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MessagePipeSupport.Generator;

[Generator]
public class RegisterRequestHandlerFilterGenerator : IIncrementalGenerator
{
    private const string RequestHandlerFilterAttributeName = "RequestHandlerFilterAttribute";
    
    private static readonly StringBuilder RegisterRequestFilterOverallBuilder = new();
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<RegisterRequestHandlerFilterModel> classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: (syntaxContext, _) => GetRegistrationData(syntaxContext))
            .Where(registrationModel => registrationModel is not null);
        
        IncrementalValueProvider<ImmutableArray<RegisterRequestHandlerFilterModel>> registrationData = classDeclarations.Collect();
        context.RegisterSourceOutput(registrationData, Execute);
    }

    private static RegisterRequestHandlerFilterModel GetRegistrationData(GeneratorSyntaxContext context)
    {
        ClassDeclarationSyntax classDeclarationSyntax = (ClassDeclarationSyntax)context.Node;
        INamedTypeSymbol symbol = context.SemanticModel.GetDeclaredSymbol(classDeclarationSyntax) as INamedTypeSymbol;
        AttributeData attributeData = symbol?.GetAttributes().FirstOrDefault(attribute =>
            attribute.AttributeClass?.Name is RequestHandlerFilterAttributeName);

        if (attributeData == null)
            return null;
        
        string fullRequestHandlerName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        bool isAsync = false;
        
        foreach (var kvp in attributeData.NamedArguments)
        {
            switch (kvp.Key)
            {
                case "IsAsync":
                    if (kvp.Value.Value != null) 
                        isAsync = (bool)kvp.Value.Value;
                    break;
            }
        }
        
        return new RegisterRequestHandlerFilterModel(fullRequestHandlerName, isAsync);
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<RegisterRequestHandlerFilterModel> models)
    {
        if (models.IsDefaultOrEmpty)
            return;

        StringBuilder registerRequestFilterBuilder = new();
        RegisterRequestFilterOverallBuilder.Clear();
        RegisterRequestFilterOverallBuilder.AppendLine("// Authored by DracoRuan");
        RegisterRequestFilterOverallBuilder.AppendLine($"// <auto-generated Request Handlers/>");
        RegisterRequestFilterOverallBuilder.AppendLine("using VContainer;");
        RegisterRequestFilterOverallBuilder.AppendLine("using MessagePipe;");
        RegisterRequestFilterOverallBuilder.AppendLine("");
        RegisterRequestFilterOverallBuilder.AppendLine("namespace MessagePipeGeneratorSupport.RequestHandlers.Generated");
        RegisterRequestFilterOverallBuilder.AppendLine("{");
        RegisterRequestFilterOverallBuilder.AppendLine($"   public static class MessagePipeRequestHandlerExtension");
        RegisterRequestFilterOverallBuilder.AppendLine("   {");
        RegisterRequestFilterOverallBuilder.AppendLine("       public static void RegisterAllRequestHandlerFilters(this IContainerBuilder builder)");
        RegisterRequestFilterOverallBuilder.AppendLine("       {");
        
        foreach (RegisterRequestHandlerFilterModel model in models)
        {
            GetGeneratedCodeForRequestHandler(model, registerRequestFilterBuilder);
        }

        RegisterRequestFilterOverallBuilder.Append(registerRequestFilterBuilder);
        RegisterRequestFilterOverallBuilder.AppendLine("       }");
        RegisterRequestFilterOverallBuilder.AppendLine("   }");
        RegisterRequestFilterOverallBuilder.AppendLine("}");
        SourceText generatedCode = SourceText.From(RegisterRequestFilterOverallBuilder.ToString(), Encoding.UTF8);
        context.AddSource("GeneratedMessagePipeRequestHandlerFiltersRegister.g.cs", generatedCode);
    }

    private static void GetGeneratedCodeForRequestHandler(RegisterRequestHandlerFilterModel requestHandlerModel,
        StringBuilder stringBuilder)
    {
        if (!requestHandlerModel.IsAsync)
            stringBuilder.AppendLine($"            builder.RegisterRequestHandlerFilter<{requestHandlerModel.FullRequestHandlerName}>();");
        else
            stringBuilder.AppendLine($"            builder.RegisterAsyncRequestHandlerFilter<{requestHandlerModel.FullRequestHandlerName}>();");
    }
}