using System.Linq;
using System.Collections.Immutable;
using System.Text;
using MessagePipeSupport.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MessagePipeSupport.Generator;

[Generator]
public class RequestHandlerGenerator : IIncrementalGenerator
{
    private const string RequestHandlerAttributeName = "RequestHandlerAttribute";
    
    private static readonly StringBuilder RequestHandlerOverallBuilder = new();
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<RequestHandlerModel> classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: (syntaxContext, _) => GetRegistrationData(syntaxContext))
            .Where(registrationModel => registrationModel is not null);
        
        IncrementalValueProvider<ImmutableArray<RequestHandlerModel>> registrationData = classDeclarations.Collect();
        context.RegisterSourceOutput(registrationData, Execute);
    }

    private static RequestHandlerModel GetRegistrationData(GeneratorSyntaxContext context)
    {
        ClassDeclarationSyntax classDeclarationSyntax = (ClassDeclarationSyntax)context.Node;
        INamedTypeSymbol symbol = context.SemanticModel.GetDeclaredSymbol(classDeclarationSyntax) as INamedTypeSymbol;
        AttributeData attributeData = symbol?.GetAttributes().FirstOrDefault(attribute =>
            attribute.AttributeClass?.Name is RequestHandlerAttributeName);

        if (attributeData == null)
            return null;
        
        string fullRequestHandlerName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string minimalRequestHandlerName = symbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
        string requestType = "int";
        string responseType = "int";
        
        foreach (var kvp in attributeData.NamedArguments)
        {
            ITypeSymbol typeSymbol;
            switch (kvp.Key)
            {
                case "RequestType":
                    typeSymbol = kvp.Value.Value as ITypeSymbol;
                    requestType = typeSymbol?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    break;
                case "ResponseType":
                    typeSymbol = kvp.Value.Value as ITypeSymbol;
                    responseType = typeSymbol?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    break;
            }
        }
        
        return new RequestHandlerModel(fullRequestHandlerName, minimalRequestHandlerName, requestType, responseType);
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<RequestHandlerModel> models)
    {
        if (models.IsDefaultOrEmpty)
            return;

        StringBuilder requestHandlerBuilder = new();
        RequestHandlerOverallBuilder.Clear();
        RequestHandlerOverallBuilder.AppendLine("// Authored by DracoRuan");
        RequestHandlerOverallBuilder.AppendLine($"// <auto-generated Request Handlers/>");
        RequestHandlerOverallBuilder.AppendLine("using VContainer;");
        RequestHandlerOverallBuilder.AppendLine("using MessagePipe;");
        RequestHandlerOverallBuilder.AppendLine("");
        RequestHandlerOverallBuilder.AppendLine("namespace MessagePipeGeneratorSupport.RequestHandlers.Generated");
        RequestHandlerOverallBuilder.AppendLine("{");
        RequestHandlerOverallBuilder.AppendLine($"   public static class MessagePipeRequestHandlerExtension");
        RequestHandlerOverallBuilder.AppendLine("   {");
        RequestHandlerOverallBuilder.AppendLine("       public static void RegisterAllRequestHandlers(this IContainerBuilder builder, MessagePipeOptions options)");
        RequestHandlerOverallBuilder.AppendLine("       {");
        
        foreach (RequestHandlerModel model in models)
        {
            GetGeneratedCodeForRequestHandler(model, requestHandlerBuilder);
        }

        RequestHandlerOverallBuilder.Append(requestHandlerBuilder);
        RequestHandlerOverallBuilder.AppendLine("       }");
        RequestHandlerOverallBuilder.AppendLine("   }");
        RequestHandlerOverallBuilder.AppendLine("}");
        SourceText generatedCode = SourceText.From(RequestHandlerOverallBuilder.ToString(), Encoding.UTF8);
        context.AddSource("GeneratedMessagePipeRequestHandlersRegister.g.cs", generatedCode);
    }

    private static void GetGeneratedCodeForRequestHandler(RequestHandlerModel requestHandlerModel,
        StringBuilder stringBuilder)
    {
        string requestType = requestHandlerModel.RequestType;
        string responseType = requestHandlerModel.ResponseType;
        stringBuilder.AppendLine($"            builder.RegisterRequestHandler<{requestType}, {responseType}, {requestHandlerModel.FullRequestHandlerName}>(options);");
    }
}