using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using VContainerSupport.Models;

namespace VContainerSupport.Generators;

[Generator]
public class RegisterInstallerOrchestrator : IIncrementalGenerator
{
    private const string AttributeShortName = "RegisterInstallerAttribute";
    private const string AttributeFullName = "RegisterInstallerAttributeAttribute";
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<InstallerRegistrationModel> classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: (syntaxContext, _) => GetRegistrationData(syntaxContext))
            .Where(registrationModel => registrationModel is not null);
        
        IncrementalValueProvider<ImmutableArray<InstallerRegistrationModel>> registrationData = classDeclarations.Collect();
        context.RegisterSourceOutput(registrationData, (spc, source) => Execute(source, spc));
    }
    
    private static InstallerRegistrationModel GetRegistrationData(GeneratorSyntaxContext context)
    {
        ClassDeclarationSyntax classDeclarationSyntax = (ClassDeclarationSyntax)context.Node;
        INamedTypeSymbol symbol = context.SemanticModel.GetDeclaredSymbol(classDeclarationSyntax) as INamedTypeSymbol;
        AttributeData attributeData = symbol?.GetAttributes().FirstOrDefault(attribute =>
            attribute.AttributeClass?.Name is AttributeFullName or AttributeShortName);

        if (attributeData == null)
            return null;

        string installerKey = null;
        string lifetimeScopeName = "ProjectLifetimeScope";
        string installerInstanceType = "PlainCSharp";
        string installerDataType = "";

        foreach (var kvp in attributeData.NamedArguments)
        {
            switch (kvp.Key)
            {
                case "InstallerKey":
                    installerKey = kvp.Value.Value?.ToString();
                    break;
                case "LifetimeScopeName":
                    lifetimeScopeName = kvp.Value.Value?.ToString();
                    break;
                case "InstallerInstanceType":
                    installerInstanceType = kvp.Value.Value?.ToString();
                    break;
                case "InstallerDataType":
                    installerDataType = kvp.Value.Value?.ToString();
                    break;
            }
        }

        return new InstallerRegistrationModel(installerKey, installerDataType, lifetimeScopeName, installerInstanceType);
    }
    
    private static void Execute(ImmutableArray<InstallerRegistrationModel> models, SourceProductionContext context)
    {
        if (models.IsDefaultOrEmpty)
            return;

        foreach (IGrouping<string, InstallerRegistrationModel> grouping in models.GroupBy(registrationModel =>
                     registrationModel.LifetimeScopeName))
        {
            foreach (InstallerRegistrationModel model in models)
            {
                StringBuilder stringBuilder = new();

                context.AddSource($"VContainer_{model.InstallerKey}Register.g.cs",
                    SourceText.From(stringBuilder.ToString(), Encoding.UTF8));
            }
        }
    }

    private SourceText GetGeneratedSourceForInstallerMonoBehaviour(InstallerRegistrationModel registrationModel)
    {
        StringBuilder stringBuilder = new();
        stringBuilder.AppendLine("// Authored by DracoRuan");
        stringBuilder.AppendLine("// <auto-generated />");
        
        stringBuilder.AppendLine("using VContainer;");
        stringBuilder.AppendLine("using VContainer.Unity;");
        stringBuilder.AppendLine("using UnityEngine;");
        stringBuilder.AppendLine("using Cysharp.Threading.Tasks;");
        stringBuilder.AppendLine("using UnityEngine.AddressableAssets;");
        stringBuilder.AppendLine("using UnityEngine.ResourceManagement.AsyncOperations;");
        
        stringBuilder.AppendLine("");
        stringBuilder.AppendLine("namespace DracoRuan.VContainerSupport.Generated");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine($"    public static class VContainer{registrationModel.LifetimeScopeName}Extensions");
        stringBuilder.AppendLine("    {");
        stringBuilder.AppendLine($"        public static UniTask RegisterInstallerAuto{registrationModel.LifetimeScopeName}(this IContainerBuilder builder)");
        stringBuilder.AppendLine("        {");
        stringBuilder.AppendLine($"              {registrationModel.InstallerDataType} installer = await InitializeInstaller({registrationModel.InstallerKey});");
        stringBuilder.AppendLine("              if (installer != null)");
        stringBuilder.AppendLine("              {");
        stringBuilder.AppendLine("                  installer.Install(builder);");
        stringBuilder.AppendLine($"                 installer.transform.SetParent({registrationModel.LifetimeScopeName}.LifetimeScopeInstallerRoot);");
        stringBuilder.AppendLine("              }");
        stringBuilder.AppendLine("        }");
        stringBuilder.AppendLine("");
        
        stringBuilder.AppendLine($"        private async UniTask<{registrationModel.InstallerDataType}> InitializeInstaller(string installerKey)");
        stringBuilder.AppendLine("        {");
        stringBuilder.AppendLine("              AsyncOperationHandle<GameObject> handle = Addressables.LoadAssetAsync<GameObject>(installerKey);");
        stringBuilder.AppendLine("              await handle;");
        stringBuilder.AppendLine("              if (handle.Status == AsyncOperationStatus.Succeeded)");
        stringBuilder.AppendLine("              {");
        stringBuilder.AppendLine("                  GameObject instance = Instantiate(handle.Result);");
        stringBuilder.AppendLine($"                 if (instance.TryGetComponent(out {registrationModel.InstallerDataType} installer))");
        stringBuilder.AppendLine("                      return installer;");
        stringBuilder.AppendLine("              }");
        stringBuilder.AppendLine("              return null;");
        stringBuilder.AppendLine("        }");
        stringBuilder.AppendLine("    }");
        stringBuilder.AppendLine("}");
        
        return SourceText.From(stringBuilder.ToString(), Encoding.UTF8);
    }
    
    private SourceText GetGeneratedSourceForInstallerScriptableObject(InstallerRegistrationModel registrationModel)
    {
        StringBuilder stringBuilder = new();
        stringBuilder.AppendLine("// Authored by DracoRuan");
        stringBuilder.AppendLine("// <auto-generated />");
        
        stringBuilder.AppendLine("using VContainer;");
        stringBuilder.AppendLine("using VContainer.Unity;");
        stringBuilder.AppendLine("using UnityEngine;");
        stringBuilder.AppendLine("using Cysharp.Threading.Tasks;");
        stringBuilder.AppendLine("using UnityEngine.AddressableAssets;");
        stringBuilder.AppendLine("using UnityEngine.ResourceManagement.AsyncOperations;");
        
        stringBuilder.AppendLine("");
        stringBuilder.AppendLine("namespace DracoRuan.VContainerSupport.Generated");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine($"    public static class VContainer{registrationModel.LifetimeScopeName}Extensions");
        stringBuilder.AppendLine("    {");
        stringBuilder.AppendLine($"        public static UniTask RegisterInstallerAuto{registrationModel.LifetimeScopeName}(this IContainerBuilder builder)");
        stringBuilder.AppendLine("        {");
        stringBuilder.AppendLine($"              {registrationModel.InstallerDataType} installer = await InitializeInstaller({registrationModel.InstallerKey});");
        stringBuilder.AppendLine("              if (installer != null)");
        stringBuilder.AppendLine("                  installer.Install(builder);");
        stringBuilder.AppendLine("        }");
        stringBuilder.AppendLine("");
        
        stringBuilder.AppendLine($"        private async UniTask<{registrationModel.InstallerDataType}> InitializeInstaller(string installerKey)");
        stringBuilder.AppendLine("        {");
        stringBuilder.AppendLine($"             AsyncOperationHandle<{registrationModel.InstallerDataType}> handle = Addressables.LoadAssetAsync<{registrationModel.InstallerDataType}>(installerKey);");
        stringBuilder.AppendLine("              await handle;");
        stringBuilder.AppendLine("              if (handle.Status == AsyncOperationStatus.Succeeded)");
        stringBuilder.AppendLine("              {");
        stringBuilder.AppendLine($"                      {registrationModel.InstallerDataType} result = handle.Result;");
        stringBuilder.AppendLine("                      return result;");
        stringBuilder.AppendLine("              }");
        stringBuilder.AppendLine("              return null;");
        stringBuilder.AppendLine("        }");
        stringBuilder.AppendLine("    }");
        stringBuilder.AppendLine("}");
        
        return SourceText.From(stringBuilder.ToString(), Encoding.UTF8);
    }
}