using System.Linq;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using VContainerSupport.Models;

namespace VContainerSupport.Generators;

[Generator]
public class RegisterServiceGenerator : IIncrementalGenerator
{
    private const string AutoRegisterServiceAttributeName = "RegisterServiceAttribute";
    
    private static readonly StringBuilder ServiceRegisterBaseBuilder = new();
    private static readonly StringBuilder ServiceRegisterNamespaceBuilder = new();
    private static readonly StringBuilder ServiceRegisterComponentBuilder = new();
    
    private static readonly StringBuilder EntryPointRegisterBaseBuilder = new();
    private static readonly StringBuilder EntryPointRegisterNamespaceBuilder = new();
    private static readonly StringBuilder EntryPointRegisterComponentBuilder = new();

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<ServiceRegistrationModel> classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: (syntaxContext, _) => GetRegistrationData(syntaxContext))
            .Where(registrationModel => registrationModel is not null);
        
        IncrementalValueProvider<ImmutableArray<ServiceRegistrationModel>> registrationData = classDeclarations.Collect();
        context.RegisterSourceOutput(registrationData, Execute);
    }

    private static ServiceRegistrationModel GetRegistrationData(GeneratorSyntaxContext context)
    {
        ClassDeclarationSyntax classDeclarationSyntax = (ClassDeclarationSyntax)context.Node;
        INamedTypeSymbol symbol = context.SemanticModel.GetDeclaredSymbol(classDeclarationSyntax) as INamedTypeSymbol;
        AttributeData attributeData = symbol?.GetAttributes().FirstOrDefault(attribute =>
            attribute.AttributeClass?.Name is AutoRegisterServiceAttributeName);

        if (attributeData == null)
            return null;

        string serviceName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string lifetimeScope = "Scoped";
        string lifetimeScopeName = "ProjectLifetimeScope";
        string minimalServiceName = symbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
        bool asImplementInterfaces = false;
        bool isEntryPoint = false;
        bool asSelf = false;
        string withKey = null;

        foreach (var kvp in attributeData.NamedArguments)
        {
            bool isTargetValueNull;
            switch (kvp.Key)
            {
                case "LifetimeScope":
                    lifetimeScope = kvp.Value.Value?.ToString();
                    break;
                case "LifetimeScopeName":
                    lifetimeScopeName = kvp.Value.Value?.ToString();
                    break;
                case "AsImplementedInterfaces":
                    isTargetValueNull = kvp.Value.Value == null;
                    asImplementInterfaces = !isTargetValueNull && (bool)kvp.Value.Value;
                    break;
                case "IsEntryPoint":
                    isTargetValueNull = kvp.Value.Value == null;
                    isEntryPoint = !isTargetValueNull && (bool)kvp.Value.Value;
                    break;
                case "AsSelf":
                    isTargetValueNull = kvp.Value.Value == null;
                    asSelf = !isTargetValueNull && (bool)kvp.Value.Value;
                    break;
                case "WithKey":
                    withKey = kvp.Value.Value?.ToString();
                    break;
            }
        }

        return new ServiceRegistrationModel(serviceName, lifetimeScope, lifetimeScopeName, minimalServiceName,
            asImplementInterfaces, isEntryPoint, asSelf, withKey);
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<ServiceRegistrationModel> models)
    {
        if (models.IsDefaultOrEmpty)
            return;

        foreach (IGrouping<string, ServiceRegistrationModel> serviceRegistrationModels in models.GroupBy(registrationModel =>
                     registrationModel.LifetimeScopeName))
        {
            ServiceRegisterBaseBuilder.Clear();
            ServiceRegisterNamespaceBuilder.Clear();
            ServiceRegisterComponentBuilder.Clear();

            EntryPointRegisterBaseBuilder.Clear();
            EntryPointRegisterNamespaceBuilder.Clear();
            EntryPointRegisterComponentBuilder.Clear();
            
            ServiceRegisterBaseBuilder.AppendLine("// Authored by DracoRuan");
            ServiceRegisterBaseBuilder.AppendLine($"// <auto-generated Register Service/>");
            ServiceRegisterBaseBuilder.AppendLine("using VContainer;");
            ServiceRegisterBaseBuilder.AppendLine("using VContainer.Unity;");
            ServiceRegisterBaseBuilder.AppendLine("");
            ServiceRegisterBaseBuilder.AppendLine($"namespace DracoRuan.VContainer{serviceRegistrationModels.Key}ServiceRegisterSupport.Generated");
            ServiceRegisterBaseBuilder.AppendLine("{");
            
            EntryPointRegisterBaseBuilder.AppendLine("// Authored by DracoRuan");
            EntryPointRegisterBaseBuilder.AppendLine($"// <auto-generated Register Service/>");
            EntryPointRegisterBaseBuilder.AppendLine("using VContainer;");
            EntryPointRegisterBaseBuilder.AppendLine("using VContainer.Unity;");
            EntryPointRegisterBaseBuilder.AppendLine("");
            EntryPointRegisterBaseBuilder.AppendLine($"namespace DracoRuan.VContainer{serviceRegistrationModels.Key}EntryPointRegisterSupport.Generated");
            EntryPointRegisterBaseBuilder.AppendLine("{");
            
            foreach (ServiceRegistrationModel registrationModel in serviceRegistrationModels)
            {
                string serviceType = registrationModel.IsEntryPoint ? "EntryPoint" : "Service";
                BuildServiceRegister(serviceRegistrationModels, registrationModel);
                BuildEntryPointRegister(serviceRegistrationModels, registrationModel);
                SourceText generatedServiceRegistrationCode = GetServiceRegistrationGeneratedCode(serviceRegistrationModels, registrationModel);
                context.AddSource($"VContainer{serviceRegistrationModels.Key}{registrationModel.MinimalServiceName}{serviceType}Register.g.cs",
                    generatedServiceRegistrationCode);
            }
            
            ServiceRegisterBaseBuilder.Append(ServiceRegisterNamespaceBuilder);
            ServiceRegisterBaseBuilder.AppendLine("");
            ServiceRegisterBaseBuilder.AppendLine($"        public static class AutoRegister{serviceRegistrationModels.Key}Services");
            ServiceRegisterBaseBuilder.AppendLine("        {");
            ServiceRegisterBaseBuilder.AppendLine($"            public static void AutoRegisterAll{serviceRegistrationModels.Key}Services(this IContainerBuilder builder)");
            ServiceRegisterBaseBuilder.AppendLine("            {");
            
            ServiceRegisterBaseBuilder.Append(ServiceRegisterComponentBuilder);
            ServiceRegisterBaseBuilder.AppendLine("            }");
            ServiceRegisterBaseBuilder.AppendLine("        }");
            ServiceRegisterBaseBuilder.AppendLine("}");
            
            EntryPointRegisterBaseBuilder.Append(EntryPointRegisterNamespaceBuilder);
            EntryPointRegisterBaseBuilder.AppendLine("");
            EntryPointRegisterBaseBuilder.AppendLine($"        public static class AutoRegister{serviceRegistrationModels.Key}EntryPoints");
            EntryPointRegisterBaseBuilder.AppendLine("        {");
            EntryPointRegisterBaseBuilder.AppendLine($"            public static void AutoRegisterAll{serviceRegistrationModels.Key}EntryPoints(this IContainerBuilder builder)");
            EntryPointRegisterBaseBuilder.AppendLine("            {");
            
            EntryPointRegisterBaseBuilder.Append(EntryPointRegisterComponentBuilder);
            EntryPointRegisterBaseBuilder.AppendLine("            }");
            EntryPointRegisterBaseBuilder.AppendLine("        }");
            EntryPointRegisterBaseBuilder.AppendLine("}");
            
            context.AddSource($"VContainer{serviceRegistrationModels.Key}ServicesRegister.g.cs",
                SourceText.From(ServiceRegisterBaseBuilder.ToString(), Encoding.UTF8));
            context.AddSource($"VContainer{serviceRegistrationModels.Key}EntryPointsRegister.g.cs",
                SourceText.From(EntryPointRegisterBaseBuilder.ToString(), Encoding.UTF8));
        }
    }

    private static SourceText GetServiceRegistrationGeneratedCode(IGrouping<string, ServiceRegistrationModel> grouping, 
        ServiceRegistrationModel registrationModel)
    {
        StringBuilder stringBuilder = new();
        stringBuilder.AppendLine("// Authored by DracoRuan");
        string serviceType = registrationModel.IsEntryPoint ? "EntryPoint" : "Service";
        stringBuilder.AppendLine($"// <auto-generated Register {registrationModel.MinimalServiceName} {serviceType}/>");
        stringBuilder.AppendLine("using VContainer;");
        stringBuilder.AppendLine("using VContainer.Unity;");
        stringBuilder.AppendLine("");
        stringBuilder.AppendLine($"namespace DracoRuan.VContainer{grouping.Key}{registrationModel.MinimalServiceName}Support.Generated");
        stringBuilder.AppendLine("{");
                
        stringBuilder.AppendLine($"    public static class VContainer{grouping.Key}{registrationModel.MinimalServiceName}{serviceType}RegisterExtensions");
        stringBuilder.AppendLine("    {");
        stringBuilder.AppendLine($"        public static void Register{grouping.Key}{registrationModel.MinimalServiceName}{serviceType}(this IContainerBuilder builder)");
        stringBuilder.AppendLine("        {");
                
        bool isEntryPoint = registrationModel.IsEntryPoint;
        string asImplementInterfaces = registrationModel.AsImplementInterfaces ? ".AsImplementedInterfaces()" : "";
        string asSelf = registrationModel.AsSelf ? ".AsSelf()" : "";
        string keyed = !string.IsNullOrEmpty(registrationModel.WithKey) ? $".Keyed({registrationModel.WithKey})" : "";
        string codeCommand = !isEntryPoint
            ? $"            builder.Register<{registrationModel.ServiceName}>(Lifetime.{registrationModel.LifetimeScope}){asImplementInterfaces}{asSelf}{keyed};"
            : $"            builder.RegisterEntryPoint<{registrationModel.ServiceName}>(Lifetime.{registrationModel.LifetimeScope}){asImplementInterfaces}{asSelf}{keyed};";
        stringBuilder.AppendLine(codeCommand);
        stringBuilder.AppendLine("        }");
        stringBuilder.AppendLine("    }");
        stringBuilder.AppendLine("}");
        return SourceText.From(stringBuilder.ToString(), Encoding.UTF8);
    }

    private static void BuildServiceRegister(IGrouping<string, ServiceRegistrationModel> grouping,
        ServiceRegistrationModel registrationModel)
    {
        if (registrationModel.IsEntryPoint)
            return;
        
        ServiceRegisterNamespaceBuilder.AppendLine($"        using DracoRuan.VContainer{grouping.Key}{registrationModel.MinimalServiceName}Support.Generated;");
        ServiceRegisterComponentBuilder.AppendLine($"                 VContainer{grouping.Key}{registrationModel.MinimalServiceName}ServiceRegisterExtensions.Register{grouping.Key}{registrationModel.MinimalServiceName}Service(builder);");
    }
    
    private static void BuildEntryPointRegister(IGrouping<string, ServiceRegistrationModel> grouping,
        ServiceRegistrationModel registrationModel)
    {
        if (!registrationModel.IsEntryPoint)
            return;
        
        EntryPointRegisterNamespaceBuilder.AppendLine($"        using DracoRuan.VContainer{grouping.Key}{registrationModel.MinimalServiceName}Support.Generated;");
        EntryPointRegisterComponentBuilder.AppendLine($"                  VContainer{grouping.Key}{registrationModel.MinimalServiceName}EntryPointRegisterExtensions.Register{grouping.Key}{registrationModel.MinimalServiceName}EntryPoint(builder);");
    }
}