using System.Linq;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using VContainerSupport.Models;

namespace VContainerSupport.Generators;

[Generator]
public class RegisterServiceGenerator : IIncrementalGenerator
{
    private const string AttributeShortName = "RegisterService";
    private const string AttributeFullName = "RegisterServiceAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<ServiceRegistrationModel> classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: (syntaxContext, _) => GetRegistrationData(syntaxContext))
            .Where(registrationModel => registrationModel is not null);
        
        IncrementalValueProvider<ImmutableArray<ServiceRegistrationModel>> registrationData = classDeclarations.Collect();
        context.RegisterSourceOutput(registrationData, (spc, source) => Execute(source, spc));
    }

    private static ServiceRegistrationModel GetRegistrationData(GeneratorSyntaxContext context)
    {
        ClassDeclarationSyntax classDeclarationSyntax = (ClassDeclarationSyntax)context.Node;
        INamedTypeSymbol symbol = context.SemanticModel.GetDeclaredSymbol(classDeclarationSyntax) as INamedTypeSymbol;
        AttributeData attributeData = symbol?.GetAttributes().FirstOrDefault(attribute =>
            attribute.AttributeClass?.Name is AttributeFullName or AttributeShortName);

        if (attributeData == null)
            return null;

        string serviceName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string lifetimeScope = "Scoped";
        string lifetimeScopeName = "ProjectLifetimeScope";
        string installerName = null;
        bool asImplementInterfaces = false;
        bool isEntryPoint = false;
        bool asSelf = false;
        string withKey = null;

        foreach (var kvp in attributeData.NamedArguments)
        {
            bool isTargetValueNull;
            switch (kvp.Key)
            {
                case "LifetimeScope":
                    lifetimeScope = kvp.Value.Value?.ToString();
                    break;
                case "LifetimeScopeName":
                    lifetimeScopeName = kvp.Value.Value?.ToString();
                    break;
                case "InstallerName":
                    installerName = kvp.Value.Value?.ToString();
                    break;
                case "AsImplementedInterfaces":
                    isTargetValueNull = kvp.Value.Value == null;
                    asImplementInterfaces = !isTargetValueNull && (bool)kvp.Value.Value;
                    break;
                case "IsEntryPoint":
                    isTargetValueNull = kvp.Value.Value == null;
                    isEntryPoint = !isTargetValueNull && (bool)kvp.Value.Value;
                    break;
                case "AsSelf":
                    isTargetValueNull = kvp.Value.Value == null;
                    asSelf = !isTargetValueNull && (bool)kvp.Value.Value;
                    break;
                case "WithKey":
                    withKey = kvp.Value.Value?.ToString();
                    break;
            }
        }

        return new ServiceRegistrationModel(serviceName, lifetimeScope, lifetimeScopeName, installerName,
            asImplementInterfaces, isEntryPoint, asSelf, withKey);
    }

    private static void Execute(ImmutableArray<ServiceRegistrationModel> models, SourceProductionContext context)
    {
        if (models.IsDefaultOrEmpty)
            return;

        foreach (IGrouping<string, ServiceRegistrationModel> grouping in models.GroupBy(registrationModel =>
                     registrationModel.LifetimeScopeName))
        {
            StringBuilder stringBuilder = new();
            stringBuilder.AppendLine("// Authored by DracoRuan");
            stringBuilder.AppendLine("// <auto-generated />");
            stringBuilder.AppendLine("using VContainer;");
            stringBuilder.AppendLine("using VContainer.Unity;");
            stringBuilder.AppendLine("");
            stringBuilder.AppendLine("namespace DracoRuan.VContainerSupport.Generated");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine($"    public static class VContainer{grouping.Key}Extensions");
            stringBuilder.AppendLine("    {");
            stringBuilder.AppendLine($"        public static void RegisterServiceAuto{grouping.Key}(this IContainerBuilder builder)");
            stringBuilder.AppendLine("        {");

            IOrderedEnumerable<ServiceRegistrationModel> serviceRegistrationModels =
                grouping.OrderByDescending(model => model.IsEntryPoint);
            foreach (ServiceRegistrationModel item in serviceRegistrationModels)
            {
                bool isEntryPoint = item.IsEntryPoint;
                string asImplementInterfaces = item.AsImplementInterfaces ? ".AsImplementedInterfaces()" : "";
                string asSelf = item.AsSelf ? ".AsSelf()" : "";
                string keyed = !string.IsNullOrEmpty(item.WithKey) ? $".Keyed({item.WithKey})" : "";
                string codeCommand = !isEntryPoint
                    ? $"            builder.Register<{item.ServiceName}>(Lifetime.{item.LifetimeScope}){asImplementInterfaces}{asSelf}{keyed};"
                    : $"            builder.RegisterEntryPoint<{item.ServiceName}>(Lifetime.{item.LifetimeScope}){asImplementInterfaces}{asSelf}{keyed};";
                stringBuilder.AppendLine(codeCommand);
            }

            stringBuilder.AppendLine("        }");
            stringBuilder.AppendLine("    }");
            stringBuilder.AppendLine("}");

            context.AddSource($"VContainer_{grouping.Key}Reg.g.cs",
                SourceText.From(stringBuilder.ToString(), Encoding.UTF8));
        }
    }
}