using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using VContainerSupport.Models;

namespace VContainerSupport.Generators;

[Generator]
public class RegisterInstallerGenerator : IIncrementalGenerator
{
    private const string AttributeShortName = "RegisterInstallerAttribute";
    private const string AttributeFullName = "RegisterInstallerAttributeAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<InstallerRegistrationModel> classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: (syntaxContext, _) => GetRegistrationData(syntaxContext))
            .Where(registrationModel => registrationModel is not null);
        
        IncrementalValueProvider<ImmutableArray<InstallerRegistrationModel>> registrationData = classDeclarations.Collect();
        context.RegisterSourceOutput(registrationData, (spc, source) => Execute(source, spc));
    }

    private static InstallerRegistrationModel GetRegistrationData(GeneratorSyntaxContext context)
    {
        ClassDeclarationSyntax classDeclarationSyntax = (ClassDeclarationSyntax)context.Node;
        INamedTypeSymbol symbol = context.SemanticModel.GetDeclaredSymbol(classDeclarationSyntax) as INamedTypeSymbol;
        AttributeData attributeData = symbol?.GetAttributes().FirstOrDefault(attribute =>
            attribute.AttributeClass?.Name is AttributeFullName or AttributeShortName);

        if (attributeData == null)
            return null;

        string installerKey = null;
        string fullInstallerName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string lifetimeScopeName = "ProjectLifetimeScope";
        string installerInstanceType = "PlainCSharp";

        foreach (var kvp in attributeData.NamedArguments)
        {
            switch (kvp.Key)
            {
                case "InstallerKey":
                    installerKey = kvp.Value.Value?.ToString();
                    break;
                case "LifetimeScopeName":
                    lifetimeScopeName = kvp.Value.Value?.ToString();
                    break;
                case "InstallerInstanceType":
                    installerInstanceType = kvp.Value.Value?.ToString();
                    break;
            }
        }

        return new InstallerRegistrationModel(installerKey, fullInstallerName, lifetimeScopeName, installerInstanceType);
    }
    
    private static void Execute(ImmutableArray<InstallerRegistrationModel> models, SourceProductionContext context)
    {
        if (models.IsDefaultOrEmpty)
            return;

        StringBuilder stringBuilder = new();
        IEnumerable<IGrouping<string, InstallerRegistrationModel>> registrationModelGroups =
            models.GroupBy(registrationModel => registrationModel.LifetimeScopeName);
        foreach (IGrouping<string, InstallerRegistrationModel> grouping in registrationModelGroups)
        {
            foreach (InstallerRegistrationModel model in grouping)
            {
                stringBuilder.Clear();
                SourceText generatedCode = model.InstallerInstanceType switch
                {
                    "PlainCSharp" => GetGeneratedSourceForInstallerPlainCSharp(model, stringBuilder),
                    "MonoBehaviour" => GetGeneratedSourceForInstallerMonoBehaviour(model, stringBuilder),
                    "ScriptableObject" => GetGeneratedSourceForInstallerScriptableObject(model, stringBuilder),
                    _ => null
                };

                if (generatedCode == null)
                    continue;
                
                context.AddSource($"VContainer_{model.InstallerKey}Register.g.cs", generatedCode);
            }
        }
    }
    
    private static SourceText GetGeneratedSourceForInstallerMonoBehaviour(InstallerRegistrationModel registrationModel, 
        StringBuilder stringBuilder)
    {
        stringBuilder.AppendLine("// Authored by DracoRuan");
        stringBuilder.AppendLine($"// <auto-generated MonoBehaviour Installer {registrationModel.FullInstallerName}/>");
        
        stringBuilder.AppendLine("using VContainer;");
        stringBuilder.AppendLine("using VContainer.Unity;");
        stringBuilder.AppendLine("using UnityEngine;");
        stringBuilder.AppendLine("using Cysharp.Threading.Tasks;");
        stringBuilder.AppendLine("using UnityEngine.AddressableAssets;");
        stringBuilder.AppendLine("using UnityEngine.ResourceManagement.AsyncOperations;");
        
        stringBuilder.AppendLine("");
        stringBuilder.AppendLine($"namespace DracoRuan.VContainer{registrationModel.LifetimeScopeName}Support.Generated");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine($"    public static class VContainer{registrationModel.LifetimeScopeName}InstallerExtensions");
        stringBuilder.AppendLine("    {");
        stringBuilder.AppendLine($"        public static UniTask RegisterInstallerAuto{registrationModel.LifetimeScopeName}(this IContainerBuilder builder)");
        stringBuilder.AppendLine("        {");
        stringBuilder.AppendLine($"              {registrationModel.FullInstallerName} installer = await InitializeInstaller({registrationModel.InstallerKey});");
        stringBuilder.AppendLine("              if (installer != null)");
        stringBuilder.AppendLine("              {");
        stringBuilder.AppendLine("                  installer.Install(builder);");
        stringBuilder.AppendLine($"                 installer.transform.SetParent({registrationModel.LifetimeScopeName}.LifetimeScopeInstallerRoot);");
        stringBuilder.AppendLine("              }");
        stringBuilder.AppendLine("        }");
        stringBuilder.AppendLine("");
        
        stringBuilder.AppendLine($"        private async UniTask<{registrationModel.FullInstallerName}> InitializeInstaller(string installerKey)");
        stringBuilder.AppendLine("        {");
        stringBuilder.AppendLine("              AsyncOperationHandle<GameObject> handle = Addressables.LoadAssetAsync<GameObject>(installerKey);");
        stringBuilder.AppendLine("              await handle;");
        stringBuilder.AppendLine("              if (handle.Status == AsyncOperationStatus.Succeeded)");
        stringBuilder.AppendLine("              {");
        stringBuilder.AppendLine("                  GameObject instance = Instantiate(handle.Result);");
        stringBuilder.AppendLine($"                 if (instance.TryGetComponent(out {registrationModel.FullInstallerName} installer))");
        stringBuilder.AppendLine("                      return installer;");
        stringBuilder.AppendLine("              }");
        stringBuilder.AppendLine("              return null;");
        stringBuilder.AppendLine("        }");
        stringBuilder.AppendLine("    }");
        stringBuilder.AppendLine("}");
        
        return SourceText.From(stringBuilder.ToString(), Encoding.UTF8);
    }
    
    private static SourceText GetGeneratedSourceForInstallerScriptableObject(InstallerRegistrationModel registrationModel,
        StringBuilder stringBuilder)
    {
        stringBuilder.AppendLine("// Authored by DracoRuan");
        stringBuilder.AppendLine($"// <auto-generated ScriptableObject Installer {registrationModel.FullInstallerName}/>");
        
        stringBuilder.AppendLine("using VContainer;");
        stringBuilder.AppendLine("using VContainer.Unity;");
        stringBuilder.AppendLine("using UnityEngine;");
        stringBuilder.AppendLine("using Cysharp.Threading.Tasks;");
        stringBuilder.AppendLine("using UnityEngine.AddressableAssets;");
        stringBuilder.AppendLine("using UnityEngine.ResourceManagement.AsyncOperations;");
        
        stringBuilder.AppendLine("");
        stringBuilder.AppendLine($"namespace DracoRuan.VContainer{registrationModel.LifetimeScopeName}Support.Generated");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine($"    public static class VContainer{registrationModel.LifetimeScopeName}InstallerExtensions");
        stringBuilder.AppendLine("    {");
        stringBuilder.AppendLine($"        public static UniTask RegisterInstallerAuto{registrationModel.LifetimeScopeName}(this IContainerBuilder builder)");
        stringBuilder.AppendLine("        {");
        stringBuilder.AppendLine($"              {registrationModel.FullInstallerName} installer = await InitializeInstaller({registrationModel.InstallerKey});");
        stringBuilder.AppendLine("              if (installer != null)");
        stringBuilder.AppendLine("                  installer.Install(builder);");
        stringBuilder.AppendLine("        }");
        stringBuilder.AppendLine("");
        
        stringBuilder.AppendLine($"        private async UniTask<{registrationModel.FullInstallerName}> InitializeInstaller(string installerKey)");
        stringBuilder.AppendLine("        {");
        stringBuilder.AppendLine($"             AsyncOperationHandle<{registrationModel.FullInstallerName}> handle = Addressables.LoadAssetAsync<{registrationModel.FullInstallerName}>(installerKey);");
        stringBuilder.AppendLine("              await handle;");
        stringBuilder.AppendLine("              if (handle.Status == AsyncOperationStatus.Succeeded)");
        stringBuilder.AppendLine("              {");
        stringBuilder.AppendLine($"                      {registrationModel.FullInstallerName} result = handle.Result;");
        stringBuilder.AppendLine("                      return result;");
        stringBuilder.AppendLine("              }");
        stringBuilder.AppendLine("              return null;");
        stringBuilder.AppendLine("        }");
        stringBuilder.AppendLine("    }");
        stringBuilder.AppendLine("}");
        
        return SourceText.From(stringBuilder.ToString(), Encoding.UTF8);
    }
    
    private static SourceText GetGeneratedSourceForInstallerPlainCSharp(InstallerRegistrationModel registrationModel, 
        StringBuilder stringBuilder)
    {
        stringBuilder.AppendLine("// Authored by DracoRuan");
        stringBuilder.AppendLine($"// <auto-generated PlainCSharp Installer {registrationModel.FullInstallerName}/>");
        
        stringBuilder.AppendLine("using VContainer;");
        stringBuilder.AppendLine("using VContainer.Unity;");
        stringBuilder.AppendLine("using UnityEngine;");
        
        stringBuilder.AppendLine("");
        stringBuilder.AppendLine($"namespace DracoRuan.VContainer{registrationModel.LifetimeScopeName}Support.Generated");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine($"    public static class VContainer{registrationModel.LifetimeScopeName}InstallerExtensions");
        stringBuilder.AppendLine("    {");
        stringBuilder.AppendLine($"        public static void RegisterInstallerAuto{registrationModel.LifetimeScopeName}(this IContainerBuilder builder)");
        stringBuilder.AppendLine("        {");
        stringBuilder.AppendLine($"              {registrationModel.FullInstallerName} installer = new {registrationModel.InstallerKey}();");
        stringBuilder.AppendLine("                installer.Install(builder);");
        stringBuilder.AppendLine("        }");
        stringBuilder.AppendLine("    }");
        stringBuilder.AppendLine("}");
        
        return SourceText.From(stringBuilder.ToString(), Encoding.UTF8);
    }
}