using System.Linq;
using System.Text;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using VContainerSupport.Models;

namespace VContainerSupport.Generators;

[Generator]
public class RegisterInstallerGenerator : IIncrementalGenerator
{
    private const string AutoRegisterInstallerAttributeName = "AutoInstallAttribute";
    
    private static readonly StringBuilder InstallerTaskStringBuilder = new();

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<AutoInstallRegistrationModel> classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: (syntaxContext, _) => GetRegistrationData(syntaxContext))
            .Where(registrationModel => registrationModel is not null);
        
        IncrementalValueProvider<ImmutableArray<AutoInstallRegistrationModel>> registrationData = classDeclarations.Collect();
        context.RegisterSourceOutput(registrationData, Execute);
    }

    private static AutoInstallRegistrationModel GetRegistrationData(GeneratorSyntaxContext context)
    {
        ClassDeclarationSyntax classDeclarationSyntax = (ClassDeclarationSyntax)context.Node;
        INamedTypeSymbol symbol = context.SemanticModel.GetDeclaredSymbol(classDeclarationSyntax) as INamedTypeSymbol;
        AttributeData attributeData = symbol?.GetAttributes().FirstOrDefault(attribute =>
            attribute.AttributeClass?.Name is AutoRegisterInstallerAttributeName);

        if (attributeData == null)
            return null;

        string installerKey = null;
        string fullInstallerName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string minimalInstallerName = symbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
        string installerInstanceType = "PlainCSharp";

        foreach (var kvp in attributeData.NamedArguments)
        {
            switch (kvp.Key)
            {
                case "InstallerKey":
                    installerKey = kvp.Value.Value?.ToString();
                    break;
                case "InstallerInstanceType":
                    installerInstanceType = kvp.Value.Value?.ToString();
                    break;
            }
        }

        return new AutoInstallRegistrationModel(installerKey, fullInstallerName, minimalInstallerName,
            installerInstanceType);
    }
    
    private static void Execute(SourceProductionContext context, ImmutableArray<AutoInstallRegistrationModel> models)
    {
        if (models.IsDefaultOrEmpty)
            return;
        
        StringBuilder installerStringBuilder = new();
        InstallerTaskStringBuilder.Clear();
        
        foreach (AutoInstallRegistrationModel model in models) 
        { 
            installerStringBuilder.Clear(); 
            SourceText generatedCode = model.InstallerInstanceType switch 
            { 
                "PlainCSharp" => GetGeneratedSourceForInstallerPlainCSharp(model, installerStringBuilder), 
                "MonoBehaviour" => GetGeneratedSourceForInstallerMonoBehaviour(model, installerStringBuilder), 
                "ScriptableObject" => GetGeneratedSourceForInstallerScriptableObject(model, installerStringBuilder), 
                _ => null
            };
            
            if (generatedCode == null) 
                continue;
            
            context.AddSource($"VContainer{model.MinimalInstallerName}Register.g.cs", generatedCode);
        }
    }
    
    private static SourceText GetGeneratedSourceForInstallerMonoBehaviour(AutoInstallRegistrationModel registrationModel, 
        StringBuilder stringBuilder)
    {
        stringBuilder.AppendLine("// Authored by DracoRuan");
        stringBuilder.AppendLine($"// <auto-generated MonoBehaviour Installer {registrationModel.FullInstallerName}/>");
        
        stringBuilder.AppendLine("using VContainer;");
        stringBuilder.AppendLine("using VContainer.Unity;");
        stringBuilder.AppendLine("using UnityEngine;");
        stringBuilder.AppendLine("using Cysharp.Threading.Tasks;");
        stringBuilder.AppendLine("using UnityEngine.AddressableAssets;");
        stringBuilder.AppendLine("using UnityEngine.ResourceManagement.AsyncOperations;");
        stringBuilder.AppendLine("using DracoRuan.Foundation.Initializers.Interfaces;");
        
        stringBuilder.AppendLine("");
        stringBuilder.AppendLine($"namespace DracoRuan.VContainerInstallerSupport.Generated");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine($"    public static class VContainer{registrationModel.MinimalInstallerName}MonoBehaviourInstallerExtensions");
        stringBuilder.AppendLine("    {");
        stringBuilder.AppendLine($"        public static async UniTask Install{registrationModel.MinimalInstallerName}(this IContainerBuilder builder)");
        stringBuilder.AppendLine("        {");
        stringBuilder.AppendLine($"              {registrationModel.FullInstallerName} installer = await InitializeInstaller(\"{registrationModel.InstallerKey}\");");
        stringBuilder.AppendLine("              if (installer != null)");
        stringBuilder.AppendLine("              {");
        stringBuilder.AppendLine("                   installer.Install(builder);");
        stringBuilder.AppendLine("                   if (installer is IAsyncInstallable installable)");
        stringBuilder.AppendLine("                         await UniTask.WaitUntil(() => installable.IsInstalled());");
        stringBuilder.AppendLine("              }");
        stringBuilder.AppendLine("        }");
        stringBuilder.AppendLine("");
        
        stringBuilder.AppendLine($"        private static async UniTask<{registrationModel.FullInstallerName}> InitializeInstaller(string installerKey)");
        stringBuilder.AppendLine("        {");
        stringBuilder.AppendLine("              AsyncOperationHandle<GameObject> handle = Addressables.LoadAssetAsync<GameObject>(installerKey);");
        stringBuilder.AppendLine("              await handle;");
        stringBuilder.AppendLine("              if (handle.Status == AsyncOperationStatus.Succeeded)");
        stringBuilder.AppendLine("              {");
        stringBuilder.AppendLine("                  GameObject instance = Object.Instantiate(handle.Result);");
        stringBuilder.AppendLine($"                  if (instance.TryGetComponent(out {registrationModel.FullInstallerName} installer))");
        stringBuilder.AppendLine("                       return installer;");
        stringBuilder.AppendLine("              }");
        stringBuilder.AppendLine("              ");
        stringBuilder.AppendLine("              Addressables.Release(handle);");
        stringBuilder.AppendLine("              return null;");
        stringBuilder.AppendLine("        }");
        stringBuilder.AppendLine("    }");
        stringBuilder.AppendLine("}");
        
        return SourceText.From(stringBuilder.ToString(), Encoding.UTF8);
    }
    
    private static SourceText GetGeneratedSourceForInstallerScriptableObject(AutoInstallRegistrationModel registrationModel,
        StringBuilder stringBuilder)
    {
        stringBuilder.AppendLine("// Authored by DracoRuan");
        stringBuilder.AppendLine($"// <auto-generated ScriptableObject Installer {registrationModel.FullInstallerName}/>");
        
        stringBuilder.AppendLine("using VContainer;");
        stringBuilder.AppendLine("using VContainer.Unity;");
        stringBuilder.AppendLine("using UnityEngine;");
        stringBuilder.AppendLine("using Cysharp.Threading.Tasks;");
        stringBuilder.AppendLine("using UnityEngine.AddressableAssets;");
        stringBuilder.AppendLine("using UnityEngine.ResourceManagement.AsyncOperations;");
        stringBuilder.AppendLine("using DracoRuan.Foundation.Initializers.Interfaces;");
        
        stringBuilder.AppendLine("");
        stringBuilder.AppendLine($"namespace DracoRuan.VContainer{registrationModel.MinimalInstallerName}Support.Generated");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine($"    public static class VContainer{registrationModel.MinimalInstallerName}ScriptableObjectInstallerExtensions");
        stringBuilder.AppendLine("    {");
        stringBuilder.AppendLine($"        public static async UniTask Install{registrationModel.MinimalInstallerName}(this IContainerBuilder builder)");
        stringBuilder.AppendLine("        {");
        stringBuilder.AppendLine($"              {registrationModel.FullInstallerName} installer = await InitializeInstaller(\"{registrationModel.InstallerKey}\");");
        stringBuilder.AppendLine("               if (installer != null)");
        stringBuilder.AppendLine("              {");
        stringBuilder.AppendLine("                   installer.Install(builder);");
        stringBuilder.AppendLine("                  if (installer is IAsyncInstallable installable)");
        stringBuilder.AppendLine("                      await UniTask.WaitUntil(() => installable.IsInstalled());");
        stringBuilder.AppendLine("              }");
        stringBuilder.AppendLine("        }");
        stringBuilder.AppendLine("");
        
        stringBuilder.AppendLine($"        private async UniTask<{registrationModel.FullInstallerName}> InitializeInstaller(string installerKey)");
        stringBuilder.AppendLine("        {");
        stringBuilder.AppendLine($"             AsyncOperationHandle<{registrationModel.FullInstallerName}> handle = Addressables.LoadAssetAsync<{registrationModel.FullInstallerName}>(installerKey);");
        stringBuilder.AppendLine("              await handle;");
        stringBuilder.AppendLine("              if (handle.Status == AsyncOperationStatus.Succeeded)");
        stringBuilder.AppendLine("              {");
        stringBuilder.AppendLine($"                      {registrationModel.FullInstallerName} result = handle.Result;");
        stringBuilder.AppendLine("                      return result;");
        stringBuilder.AppendLine("              }");
        stringBuilder.AppendLine("              ");
        stringBuilder.AppendLine("              Addressables.Release(handle);");
        stringBuilder.AppendLine("              return null;");
        stringBuilder.AppendLine("        }");
        stringBuilder.AppendLine("    }");
        stringBuilder.AppendLine("}");
        
        return SourceText.From(stringBuilder.ToString(), Encoding.UTF8);
    }
    
    private static SourceText GetGeneratedSourceForInstallerPlainCSharp(AutoInstallRegistrationModel registrationModel, 
        StringBuilder stringBuilder)
    {
        stringBuilder.AppendLine("// Authored by DracoRuan");
        stringBuilder.AppendLine($"// <auto-generated PlainCSharp Installer {registrationModel.FullInstallerName}/>");
        
        stringBuilder.AppendLine("using VContainer;");
        stringBuilder.AppendLine("using VContainer.Unity;");
        stringBuilder.AppendLine("using Cysharp.Threading.Tasks;");
        stringBuilder.AppendLine("using UnityEngine;");
        stringBuilder.AppendLine("using DracoRuan.Foundation.Initializers.Interfaces;");
        
        stringBuilder.AppendLine("");
        stringBuilder.AppendLine($"namespace DracoRuan.VContainer{registrationModel.MinimalInstallerName}Support.Generated");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine($"    public static class VContainer{registrationModel.MinimalInstallerName}PlainCSharpInstallerExtensions");
        stringBuilder.AppendLine("    {");
        stringBuilder.AppendLine($"        public static async UniTask Install{registrationModel.MinimalInstallerName}(this IContainerBuilder builder)");
        stringBuilder.AppendLine("        {");
        stringBuilder.AppendLine($"              {registrationModel.FullInstallerName} installer = new {registrationModel.FullInstallerName}();");
        stringBuilder.AppendLine("              installer.Install(builder);");
        stringBuilder.AppendLine("              if (installer is IAsyncInstallable installable)");
        stringBuilder.AppendLine("                  await UniTask.WaitUntil(() => installable.IsInstalled());");
        stringBuilder.AppendLine("        }");
        stringBuilder.AppendLine("    }");
        stringBuilder.AppendLine("}");
        
        return SourceText.From(stringBuilder.ToString(), Encoding.UTF8);
    }
}