using System;
using System.Collections.Generic;
using System.Text;

namespace DracoRuan.PrebuildServices.MobileVibration.Editor
{
    /// <summary>One constant in the generated file.</summary>
    public readonly struct VibrationIdMember
    {
        public VibrationIdMember(string memberName, string value, string ownerPath)
        {
            this.MemberName = memberName;
            this.Value = value;
            this.OwnerPath = ownerPath;
        }

        public string MemberName { get; }
        public string Value { get; }

        /// <summary>Becomes the member's XML doc, so hovering it names the asset to open.</summary>
        public string OwnerPath { get; }
    }

    /// <summary>
    /// Builds the text of the generated <c>VibrationId</c> file.
    /// </summary>
    /// <remarks>
    /// <para>Pure: no Unity API, no file access, no AssetDatabase. This is the risky half of the
    /// generator kept testable, exactly as <c>AudioIdSource</c> is on the audio side.</para>
    ///
    /// <para>Unlike <c>AudioIdSource</c>, this renders a single class. There is no second group to
    /// render: a vibration has no channel/bus concept, so there is nothing matching
    /// <c>AudioChannelId</c> to generate here.</para>
    /// </remarks>
    public sealed class VibrationIdSource
    {
        /// <summary>The header marker analyzers and IDEs look for to skip a generated file.</summary>
        public const string GeneratedMarker = "<auto-generated>";

        private const int HeaderScanLines = 12;

        /// <remarks>
        /// A character bound as well as a line bound, because a file with no line breaks at all is
        /// otherwise one enormous "first line" in which the marker could sit anywhere. The real
        /// header puts it inside the first hundred characters.
        /// </remarks>
        private const int HeaderScanCharacters = 512;

        private readonly string _namespaceName;
        private readonly List<VibrationIdMember> _members;
        private readonly string _newLine;

        private VibrationIdSource(string namespaceName, List<VibrationIdMember> members, string newLine)
        {
            this._namespaceName = namespaceName;
            this._members = members;
            this._newLine = newLine;
        }

        /// <summary>Prepares a render, sorting the members into a stable order.</summary>
        public static VibrationIdSource ForMembers(
            string namespaceName, IReadOnlyList<VibrationIdMember> members, string newLine)
        {
            List<VibrationIdMember> sorted = new List<VibrationIdMember>(members?.Count ?? 0);

            for (int i = 0; i < (members?.Count ?? 0); i++)
                sorted.Add(members[i]);

            sorted.Sort(static (left, right) => string.CompareOrdinal(left.Value, right.Value));

            return new VibrationIdSource(namespaceName, sorted, string.IsNullOrEmpty(newLine) ? "\n" : newLine);
        }

        /// <summary>The whole file, ready to write.</summary>
        public string Render()
        {
            StringBuilder builder = new StringBuilder(512);

            this.RenderHeader(builder);

            builder.Append("using System.Collections.Generic;").Append(this._newLine);
            builder.Append(this._newLine);
            builder.Append("namespace ").Append(this._namespaceName).Append(this._newLine);
            builder.Append('{').Append(this._newLine);

            this.RenderClass(builder);

            builder.Append('}').Append(this._newLine);

            return builder.ToString();
        }

        /// <summary>
        /// Whether <paramref name="existingText"/> carries this generator's header.
        /// </summary>
        /// <remarks>
        /// The guard that stops the tool overwriting a hand-written file that happens to sit at the
        /// target path. Only the first few lines count, so a marker quoted further down the file
        /// cannot be mistaken for a header.
        /// </remarks>
        public static bool IsGeneratedFile(string existingText)
        {
            if (string.IsNullOrEmpty(existingText))
                return false;

            int line = 0;
            int start = 0;
            int limit = Math.Min(existingText.Length, HeaderScanCharacters);

            while (line < HeaderScanLines && start < limit)
            {
                int end = existingText.IndexOf('\n', start);
                if (end < 0 || end > limit)
                    end = limit;

                if (existingText.IndexOf(GeneratedMarker, start, end - start, StringComparison.Ordinal) >= 0)
                    return true;

                start = end + 1;
                line++;
            }

            return false;
        }

        /// <summary>
        /// The line ending <paramref name="text"/> already uses, so a rewrite never mixes them.
        /// </summary>
        public static string DetectNewLine(string text)
        {
            if (!string.IsNullOrEmpty(text) && text.IndexOf("\r\n", StringComparison.Ordinal) >= 0)
                return "\r\n";

            return "\n";
        }

        private void RenderHeader(StringBuilder builder)
        {
            builder.Append("//------------------------------------------------------------------------------")
                .Append(this._newLine);
            builder.Append("// ").Append(GeneratedMarker).Append(this._newLine);
            builder.Append("//     Generated by the Vibration Manager (Tools/Foundations/Vibration Editor/Vibration Manager).")
                .Append(this._newLine);
            builder.Append("//").Append(this._newLine);
            builder.Append("//     Do not edit this file by hand. The next generation rewrites all of it.")
                .Append(this._newLine);
            builder.Append("//     To add, rename or remove an identifier, change the VibrationEntry asset and")
                .Append(this._newLine);
            builder.Append("//     press \"Generate Ids\".").Append(this._newLine);
            builder.Append("//").Append(this._newLine);
            builder.Append("//     VibrationId: ").Append(this._members.Count).Append(this._newLine);
            builder.Append("// </auto-generated>").Append(this._newLine);
            builder.Append("//------------------------------------------------------------------------------")
                .Append(this._newLine);
            builder.Append(this._newLine);
        }

        private void RenderClass(StringBuilder builder)
        {
            builder.Append("    /// <summary>Compile-time names for every VibrationEntry asset in the project.</summary>")
                .Append(this._newLine);
            builder.Append("    public static class VibrationId").Append(this._newLine);
            builder.Append("    {").Append(this._newLine);

            for (int i = 0; i < this._members.Count; i++)
            {
                VibrationIdMember member = this._members[i];

                if (!string.IsNullOrEmpty(member.OwnerPath))
                    builder.Append("        /// <summary>").Append(member.OwnerPath).Append("</summary>")
                        .Append(this._newLine);

                builder.Append("        public const string ").Append(member.MemberName).Append(" = ")
                    .Append(Quote(member.Value)).Append(';').Append(this._newLine);
                builder.Append(this._newLine);
            }

            builder.Append("        private static readonly string[] AllIds =").Append(this._newLine);
            builder.Append("        {").Append(this._newLine);

            for (int i = 0; i < this._members.Count; i++)
                builder.Append("            ").Append(this._members[i].MemberName).Append(',').Append(this._newLine);

            builder.Append("        };").Append(this._newLine);
            builder.Append(this._newLine);
            builder.Append("        /// <summary>Every identifier above, in declaration order.</summary>")
                .Append(this._newLine);
            builder.Append("        public static IReadOnlyList<string> All => AllIds;").Append(this._newLine);
            builder.Append("    }").Append(this._newLine);
        }

        /// <remarks>
        /// The id charset cannot produce any of these, but the renderer must not depend on its
        /// caller having validated first: a generator that can emit a broken literal is a generator
        /// that eventually does.
        /// </remarks>
        private static string Quote(string value)
        {
            StringBuilder builder = new StringBuilder(value.Length + 2);
            builder.Append('"');

            foreach (char character in value)
            {
                switch (character)
                {
                    case '\\':
                        builder.Append("\\\\");
                        break;
                    case '"':
                        builder.Append("\\\"");
                        break;
                    case '\n':
                        builder.Append("\\n");
                        break;
                    case '\r':
                        builder.Append("\\r");
                        break;
                    case '\t':
                        builder.Append("\\t");
                        break;
                    default:
                        builder.Append(character);
                        break;
                }
            }

            builder.Append('"');
            return builder.ToString();
        }
    }
}
